version: '3.8'

services:
  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    profiles:
      - donotstart
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform
    ports:
      - "5432"
  admin:
    build:
      context: ./docker/go/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/admin:/admins  # Adjusted path to main.go
      - ./.go/pkg:/go/pkg
      - ./.admin_go_cache:/go-cache
    working_dir: /admins
    ports:
      - "5006:5006"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - db
  student:
    build:
      context: ./docker/go/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/student:/students
      - ./.go/pkg:/go/pkg # Consider separate volume for each service
      - ./.student_go_cache:/go-cache # Use individual cache per service
    working_dir: /students
    ports:
      - "8082:8082" # Use unique port for each service
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - db
  teacher:
    build:
      context: ./docker/go/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/teacher:/teachers
      - ./.go/pkg:/go/pkg # Consider separate volume for each service
      - ./.teacher_go_cache:/go-cache # Use individual cache per service
    working_dir: /teachers
    ports:
      - "8083:8083" # Use unique port for each service
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - db
  
  app:
    build:
      context: ./docker/go/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/gateway:/gateway
      - ./.go/pkg:/go/pkg # Consider separate volume for each service
      - ./.gateway_go_cache:/go-cache # Use individual cache per service
    working_dir: /gateway
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - admin
      - student
      - teacher
      - db
