-- Insert questions from 1 to 20
INSERT INTO "question" ("text", "teacher_id") VALUES
    ('Allergiya nima?', '1'),
    ('Biologik allergenlarga kiradi', '1'),
    ('Gumoral shok sababi:', '1'),
    ('Gemotransfuziyadan keyin tekshirish shart emas:', '1'),
    ('Normada chaqaloqlarning nafas olish soni 1 daqiqada qancha?', '1'),
    ('Bronxial astmaga xarakterli bo''lgan simtomlar:', '1'),
    ('Termik kuyishlarda asosiy shoshilinch tibbiy yordam:', '1'),
    ('Yurak - o''pka reanimatsiyasining asoratlari:', '1'),
    ('Miokard infarktini medikamentoz davolashda eng avval qo''llaniladigan preparatlarni ko''rsating:', '1'),
    ('Gipertoniya kasalligi bilan kasallangan bemorda obyektiv tekshiruvda quyidagilar aniqlandi:', '1'),
    ('Oshqozon yarasi perforasiyasiga xos simptomlar:', '1'),
    ('Tungi siydik tutolmaslik nima deb ataladi?', '1'),
    ('Vaqtinchalik qon to''xtatish usuli', '1'),
    ('Yurak - o''pka reanimasiyasining o''tkazilmaydigan holatlar', '1'),
    ('Qon ketishini to''xtatish usullari farqlanadi:', '1'),
    ('Qon ketishining og''ir a’soratini aniqlang', '1'),
    ('Qaysi kasalliklarda qon ivishi sekinlashadi:', '1'),
    ('O''pkadan qon ketish belgilari:', '1'),
    ('O''tkir siydik tutilishida shoshilinch yordam:', '1'),
    ('Gipertonik krizda kaysi dori qo''llanilmaydi?', '1');
-- Insert questions from 21 to 41
INSERT INTO "question" ("text", "teacher_id") VALUES
    ('O''tkir qoringa gumon bo''lganda qanday qo''shimcha diagnostik tekshiruvlar o''tkazish kerak:', '1'),
    ('Chaqaloqlarda yurak - o''pka reanimatsiyasi o''tkazilishida yurak massaji va nafas nisbati qanday?', '1'),
    ('Tomir urishini sekinlashishi qanday nomlanadi?', '1'),
    ('Siydik tutilishi nima deyiladi', '1'),
    ('Jgut qo''yishning a’sorati:', '1'),
    ('Oshqozon-ichakdan qon ketish belgilari:', '1'),
    ('Plevra bo’shlig''ida yiring va havo borligi nima deyiladi?', '1'),
    ('Qon ketishida ishlatiladigan dori preparatlarni belgilang?', '1'),
    ('Quturish qanday bosqichlarda kechadi?', '1'),
    ('Tizza soxasiga qo''yiladigan bog''lam:', '1'),
    ('Diuretiklar va degidratsiyalovchi vositalar guruxini aniqlang?', '1'),
    ('Kuyish shokning erektil fazasidagi asosiy belgilar:', '1'),
    ('Antropometriya o''lchamlari bu:', '1'),
    ('Rektomanoskopiya tekshirish usuli bu-:', '1'),
    ('Irrigoskopiya qanday tekshirish usuli?', '1'),
    ('Normada bolalarning nafas olish soni 1 daqiqada qancha?', '1'),
    ('Nosteriod yallig''lanishga qarshi preparatni aniqlang?', '1'),
    ('Arterial qon ketishini uzil-kesil to’xtatish usulini aniqlang:', '1'),
    ('Antiseptika nima?', '1'),
    ('"Anesteziya" atamasi nimani anglatadi?', '1');
-- Insert questions from 40 to 101
INSERT INTO "question" ("text", "teacher_id") VALUES
    ('"Anesteziya" atamasi nimani anglatadi?', '1'),
    ('Qon ivuvchanligi va fibrinolizga ta''sir qiluvchi preparatlar qatorini aniqlang:', '1'),
    ('Kislorod bilan davolash usuli qanday nomlanadi?', '1'),
    ('Nafas yo''llari orqali kiruvchi zaxarli moddani aniklang:', '1'),
    ('Miorelaksantlarni nima maqsadda qo''llaniladi?', '1'),
    ('Eritrositlar va gemoglobinning pasayishi nimaga sabab bo''ladi?', '1'),
    ('Urologik bemorlarga xos simptomni aniqlang:', '1'),
    ('1 yoshdan 8 yoshgacha bolalarda tashqi yurak massaji quyidagicha amalga oshiriladi:', '1'),
    ('Zaharlanishlarda oshqozon yuvish uchun qancha suv kerak buladi?', '1'),
    ('Shokning erektil bosqichida qanday o''zgarish bo''ladi?', '1'),
    ('Qoqsholni oldini olish uchun qilinadigan choralar:', '1'),
    ('Kuyishda birinchi yordamga kirmaydi?', '1'),
    ('Zaxarli modda teri orqali kirganda qanday muolaja qilinadi?', '1'),
    ('O''tkir buyrak sanchig''ida shoshilinch yordam:', '1'),
    ('Jaroxat infektsiyasini oldini olishning eng samarali usuli:', '1'),
    ('Quturishning erta klinik belgilari:', '1'),
    ('Kichik qon aylanish doirasi qayerdan boshlanadi?', '1'),
    ('Buyrakda siydik ajralishini to''xtashi nima deb ataladi?', '1'),
    ('Allergik reaktsiyaning og''ir turi', '1'),
    ('Strangulyasion asfiksiya bu?', '1'),
    ('Gemostatiklar to''g''ri ko''rsatilgan qatorni ko''rsating:', '1'),
    ('Giperglikemik - diabet komasida qon taxlilida nima aniqlanadi?', '1'),
    ('O''tkir infarkt miokarda EKG a’lomatlarining o’zgarishi:', '1'),
    ('Giperglikemik komada qanday preparat ishlatiladi?', '1'),
    ('SanPIN 03.42.17 nima xaqida?', '1'),
    ('Dori vositalarining nojo''ya ta''siri:', '1'),
    ('Klinik o''limni belgilari?', '1'),
    ('Kuyishning torpid fazasidagi asosiy belgilar:', '1'),
    ('Turli kasalliklar va intoksikasiyalar tufayli yuqori asab faoliyatining so''nishi', '1'),
    ('Kuchli ta''surotlarga nisbatan markaziy asab tizimining qaytargan javob reaktsiyasi', '1'),
    ('Gipersalivatsiyaning oldini olish uchun qaysi dori qo''llaniladi?', '1'),
    ('Yorug''lik ta’sirisiz ko''z qorachig''ini kengayishi?', '1'),
    ('Churra bu?', '1'),
    ('20 % li sovun eritmasini tayyorlab bering:', '1'),
    ('Qaysi qatorda gormonal preparatlar to''g''ri ko''rsatilgan?', '1'),
    ('Nikturiya nima?', '1'),
    ('Glomerulonefrit nima?', '1'),
    ('Qon guruhlarini aniqlash uchun nimadan foydalaniladi?', '1'),
    ('"Mendelson sindromi"ning asosiy sababini ko''rsating?', '1'),
    ('Bemorni ekstubasiya qilishga asosiy ko''rsatmalar qaysi qatorda to''g''ri ko''rsatilgan?', '1'),
    ('Og''ir travmalar natijasida kelib chiqadigan shok', '1'),
    ('Premedikasiyadan bosh maqsad:', '1'),
    ('Gipertermiyada birinchi yordam qanday bo''ladi?', '1'),
    ('Hamshiralik ishi asoschisi kim?', '1'),
    ('Premedikasiya nima?', '1'),
    ('Jaroxatlangan suyak va bo''g''imlar yuzasini xarakatstlantirish bu:', '1'),
    ('Kuyishning nechta darajasi farqlanadi?', '1'),
    ('Degidratasiya nima?', '1'),
    ('Gipoksiya nima?', '1'),
    ('Asfiksiya nima?', '1'),
    ('Antidotlar kanday ta''sir ko''rsatadi?', '1'),
    ('Adsorbentlar qanday ta''sir ko’rsatadi?', '1'),
    ('Gemodializga ko''rsatma bo''ladigan kasallikni aniqlang', '1'),
    ('Qusishga qarshi preparatni aniqlang:', '1'),
    ('Yurak ishemik kasalliklariga kirmaydi?', '1'),
    ('Yurak ishemik kasalliklarini davolashda ishlatiladi', '1'),
    ('O''tkir appenditsitni davolash usuliga kiradi?', '1'),
    ('Chaqaloqlarda tashqi yurak massaji quyidagcha amalga oshiriladi?', '1'),
    ('77 yoshar ayolda to''satdan chap qo''l va chap yuz soxasida bo''shashish, so''zlashish xolati qiyinlashdi. Yuzaga kelgan vaziyatda qanday xolat xaqida fikr yuritish mumkin?', '1'),
    ('Qon tomirlarni toraytiruvchi preparatni aniqlang:', '1'),
    ('Miokard infarktiga sabab bo''lmaydi:', '1'),
    ('Talvasada bemor xolatiga xavf soluvchi xolat nima?', '1');
