-- Insert choices for questions from 40 to 101
INSERT INTO "choice" ("text", "question_id", "is_correct") VALUES
    ('1og''riqsizlantirish', 40, true),
    ('to’g’ri javob yo’q', 40, false),
    ('neyro-vegetativ blokada', 40, false),
    ('jonlantirish', 40, false),
    ('1barcha javoblar to''g''ri', 41, true),
    ('geparin', 41, false),
    ('vikasol', 41, false),
    ('aminakapronovaya kislota, ditsinon', 41, false),
    ('1Oksigenoterapiya', 42, true),
    ('gidroterapiya', 42, false),
    ('fitoterapiya', 42, false),
    ('girudoterapiya', 42, false),
    ('is gazi', 43, true),
    ('morfin', 43, false),
    ('ilon zaxri', 43, false),
    ('vodorod peroksid', 43, false),
    ('tana mushaklari tonusini bo''shashtirish uchun', 44, true),
    ('tana mushaklari tonusini oshirish uchun', 44, false),
    ('tana mushaklari qo''zg''aluvchanligini oshirish uchun', 44, false),
    ('qon bosimini tushurish uchun', 44, false),
    ('To’qimalarga kislorod tashib berish xususiyatining pasayishiga', 45, true),
    ('To''qimalarga oqsillarning tashish xususiyatining pasayishiga', 45, false),
    ('To''qimalarga uglevodlar tashish xususiyatinigg pasayishiga', 45, false),
    ('To''qimalarga mikroelementlar tashish xususiyatining pasayishiga', 45, false),
    ('gematuriya', 46, true),
    ('disfagiya', 46, false),
    ('axiliya', 46, false),
    ('melanxoliya', 46, false),
    ('bir qo''lning kaft asosi bilan', 47, true),
    ('o''rta barmoq uchlari bilan', 47, false),
    ('ikki qo''lning kaft asoslari bilan', 47, false),
    ('to''g''ri javob yo''q', 47, false),
    ('10-15 l uy haroratdagi suv', 48, true),
    ('2 - 3 stakan iliq suv', 48, false),
    ('2 - 3 litr sovuq suv', 48, false),
    ('oqozoni yuvish shart emas', 48, false),
    ('ko''z qorachig''i kengaygan, yuzlari qizargan, AB birmuncha baland', 49, true),
    ('AB 100/60 mm simob ustuni, puls tezlashgan, terisi oqargan', 49, false),
    ('bemorning rangi bo''zargan, sovuq ter bosgan, kam gapiradi', 49, false),
    ('bemor savollarga qiyinchillik bilan javob beradi, terisi oqargan, puls 130marta ipsimon', 49, false),
    ('jaroxatni yot jismlardan tozalash, qoqshol anatoksini va qoqsholga qarshi zardob qilish', 50, true),
    ('axoli orasida sanitar ishlarini olib borish', 50, false),
    ('jaroxatni o''lik to''qimadan tozalash, travmatizmga qarshi kurashish', 50, false),
    ('barcha mollarni veterinar nazoratdan o''tkazish', 50, false),
    ('kuygan joyga jgut quyish', 51, true),
    ('og''riq koldiruvchi preparatlarni qo''llash', 51, false),
    ('yurak glikozidlarini qo''llash', 51, false),
    ('shokka qarshi chora - tadbirlar', 51, false),
    ('oqar suvda yuviladi', 52, true),
    ('spirt suriladi', 52, false),
    ('malxam suriladi', 52, false),
    ('yod eritmasi suriladi', 52, false),
    ('spazmolitiklarni qo''llash', 53, true),
    ('og''riqsizlantirish', 53, false),
    ('kateter quyish', 53, false),
    ('Garmonoterapiya', 53, false),
    ('jaroxatga birlamchi jarroxlik ishlovini berish', 54, true),
    ('aseptik bog''lam qo''yish', 54, false),
    ('antibiotiklarni venaga yuborish', 54, false),
    ('jaroxatga proteolitik fermentlar yuborish', 54, false),
    ('tishlangan sohada og''rik', 55, true),
    ('eyforiya', 55, false),
    ('krepitasiya', 55, false),
    ('trizm', 55, false),
    ('o''ng qorinchadan', 56, true),
    ('o''ng bo''lmachadan', 56, false),
    ('chap bo''lmachadan', 56, false),
    ('chap qorinchadan', 56, false),
    ('Anuriya', 57, true),
    ('gematuriya', 57, false),
    ('oliguriya', 57, false),
    ('ishuriya', 57, false),
    ('anafilaktik shok', 58, true),
    ('dermatit', 58, false),
    ('Kvinke shishi', 58, false),
    ('eshakyemi', 58, false),
    ('bo''yin bo''g''ilishi ezilishi oqibatida kekirdak va tomoq og''rishi', 59, true),
    ('nafas yo''llari to''silib, ulardan xavo o''tmay qolishidir', 59, false),
    ('nafas yo''llari obstruktsiyasi', 59, false),
    ('bo''g''ilish oqibatida o''pkani ezilishi', 59, false),
    ('aminokapron kislota, vikasol, disinon, kaltsiy xlorid', 60, true),
    ('aminokapron kislota, vikasol, askorbin kislota, kaltsiy xlorid', 60, false),
    ('aminokapron kislota, vikasol, disinon, vitamin E', 60, false),
    ('vitaminlar', 60, false),
    ('qand miqdorining oshib ketishi', 61, true),
    ('neytrofiloz', 61, false),
    ('L-xujayralari', 61, false),
    ('qand miqdorining pasayib ketishi', 61, false),
    ('xamma javoblar to''g''ri', 62, true),
    ('T - tishi manfiy', 62, false),
    ('Q-patologik', 62, false),
    ('ST-segmentini qo''tarilishi', 62, false),
    ('insulin 40 TV vena ichiga', 63, true),
    ('glyukoza 40 % vena ichiga', 63, false),
    ('natriy bikarbonat 4%', 63, false),
    ('reopoliglyukin 400,0', 63, false),
    ('Sog''liqni saqlash tizimidagi davolash profilaktika muassasalarida sanitar- gigiyenik, epidemiyaga va dezinfeksiya tartibiga rioya qilish haqida', 64, true),
    ('OITS profilaktikasi haqida', 64, false),
    ('yuqumli kasalliklarni oldini olish haqida', 64, false),
    ('yangi tug''ilgan chaqaloqlar parvarishi haqida', 64, false),
    ('anafilaktik shok', 65, true),
    ('infektsion kasallik', 65, false),
    ('modda almashinuvi buzilishi kasalligi', 65, false),
    ('autoimmun kasallik', 65, false),
    ('yurak va o''pka faoliyatini yo''qligi, arefleksiya', 66, true),
    ('AD pasayishi va bradikardiya;', 66, false),
    ('blak arteriyasida pulsni yo''qligi', 66, false),
    ('murda dog''larini paydo bo''lishi', 66, false),
    ('rangparlik, Q/B pasayishi va tomir urishining ipsimon bo''lishi', 67, true),
    ('sovuq ter bosishi, o''zini qayerga qo''yishni bilmaslik', 67, false),
    ('og''riqdan baqirish, asabiylik, qaltirish', 67, false),
    ('oxsillinlanish, yonboshlash, tana harorati tushishi', 67, false),
    ('unvonlarga raqobatlashishga bor', 68, true),
    ('qon qoplamaga bor', 68, false),
    ('onkologik jarohatlar ko''rishiga bor', 68, false),
    ('oqar suvda yuvishga bor', 68, false),
    ('barcha javoblar to''g''ri', 69, true),
    ('terapiya', 69, false),
    ('sanatsiya', 69, false),
    ('oila a\'zolari bilan suhbatlashish', 69, false),
    ('bilim darajasi pasayishi', 70, true),
    ('tonguqlik', 70, false),
    ('jarrohlik', 70, false),
    ('parvozdilik', 70, false),
    ('kafein', 71, true),
    ('adrenalin', 71, false),
    ('atropin', 71, false),
    ('magnezist', 71, false),
    ('sokolaga yo''l berish', 72, true),
    ('parafilaktik asalarga yo''l berish', 72, false),
    ('kompressor qo''ymaslik', 72, false),
    ('krovalojni aniq emaslik', 72, false),
    ('9 kun', 73, true),
    ('5 kun', 73, false),
    ('7 kun', 73, false),
    ('12 kun', 73, false),
    ('Qon tashqi bo''lgan narsa bilan borish', 74, true),
    ('Zararkunandali kasalliklarning ta''minoti', 74, false),
    ('Sanitariya-higiyena qo''llab-quvvatlash tizimi', 74, false),
    ('Olish yo''li tajribasi', 74, false),
    ('Antigistamin tarkibidagi preparatlarni qo''llash', 75, true),
    ('Bronholitiklarni qo''llash', 75, false),
    ('Antibiotiklarni qo''llash', 75, false),
    ('Vazodilatatorlarini qo''llash', 75, false),
    ('biokimyoviy', 76, true),
    ('bobot', 76, false),
    ('kimyo', 76, false),
    ('fizika', 76, false),
    ('Kvarteron', 77, true),
    ('Botsvany', 77, false),
    ('Fagotsity', 77, false),
    ('Eritrotsity', 77, false),
    ('antigistamin', 78, true),
    ('biostimulyator', 78, false),
    ('depressor', 78, false),
    ('interferon', 78, false),
    ('adenozin', 79, true),
    ('amitriptilin', 79, false),
    ('propranolol', 79, false),
    ('sulfasalazin', 79, false),
    ('mioglobini jizilatishning asosiy nusxasi', 80, true),
    ('plazmodi asosiy nusxasi', 80, false),
    ('eritrositlarni oksigenlantirishning asosiy nusxasi', 80, false),
    ('endoplasmatik tikuvchilar asosiy nusxasi', 80, false),
    ('yassi shlangni qutqarish', 81, true),
    ('korobka barmoq', 81, false),
    ('korgohni oson ekanligini o\'rganish', 81, false),
    ('hossizlikni o\'rganish', 81, false),
    ('endokrin', 82, true),
    ('otit', 82, false),
    ('oftalmolog', 82, false),
    ('narkolog', 82, false),
    ('avtoimmun', 83, true),
    ('nervlilik', 83, false),
    ('tuberkulez', 83, false),
    ('genetika', 83, false),
    ('sovuq terapiya', 84, true),
    ('uyquga olish', 84, false),
    ('ko''rsatkichlar', 84, false),
    ('prokoldash', 84, false),
    ('atropin', 85, true),
    ('pentoxifylline', 85, false),
    ('protamin sulfat', 85, false),
    ('doxycycline', 85, false),
    ('C-reaktiv protein', 86, true),
    ('ALT', 86, false),
    ('AST', 86, false),
    ('UREA', 86, false),
    ('vazodilatatorlar', 87, true),
    ('antibiotiklar', 87, false),
    ('antiagregantlar', 87, false),
    ('analgetiklar', 87, false),
    ('Qog''oz yuklari bo''yicha belgilangan saytlarga kirib, asosiy axborotlar bilan tanishish', 88, true),
    ('Ozmas axborot yuklarini olishga qodir bo''lgan', 88, false),
    ('Ozini ayrim o''quv yuklari bilan sinab ko''rishga qodir bo''lgan', 88, false),
    ('Ingliz tilida axborot manbalari bilan tanishish', 88, false),
    ('1% % 200 - 300 mg oralga, 0,5 % % 400 - 600 mg /l vena ichiga', 89, true),
    ('10 % 20 ml', 89, false),
    ('3 % 400 - 800 ml', 89, false),
    ('15 % 20 - 40 mg oralga', 89, false),
    ('saf hiyladagi suvni boshqarib qolish', 90, true),
    ('Jihozga elektrikni qo''llab-quvvatlash', 90, false),
    ('Jihozga ularni qo''llab-quvvatlash', 90, false),
    ('Jihozga avtomatik qo''llab-quvvatlash', 90, false),
    ('giperkalsemiya', 91, true),
    ('giperglikemiya', 91, false),
    ('giponatriyemiya', 91, false),
    ('gipokalsemiya', 91, false),
    ('Qondagi gliyukoza miqdori', 92, true),
    ('Bir yarim qutri', 92, false),
    ('Bir yuzdaq bir qutri', 92, false),
    ('Bir yuzdaq to‘ldir', 92, false),
    ('yurakka toqat kiritilishi', 93, true),
    ('bezakning ko\'tarilishi', 93, false),
    ('sarkopeniyadan kenja ko‘tarilishi', 93, false),
    ('ayolning kuchli eshik-kirish jarayonlari', 93, false),
    ('propranolol', 94, true),
    ('aminofilin', 94, false),
    ('aminokapron kislota', 94, false),
    ('aminoglikozid', 94, false),
    ('isqotlar', 95, true),
    ('shakar', 95, false),
    ('oqsimliklar', 95, false),
    ('hayvonlar', 95, false),
    ('progesteron', 96, true),
    ('kortizol', 96, false),
    ('vasopressin', 96, false),
    ('insulin', 96, false),
    ('ayollar ko''chirilganni yutib olishi', 97, true),
    ('ayollar ko''chirilganni olib qo''yish', 97, false),
    ('ayollar suyuqligini ta''minlash', 97, false),
    ('ayollar ko''chirilganni ko‘tarish', 97, false),
    ('biyokimyoviy', 98, true),
    ('kimyo', 98, false),
    ('bobot', 98, false),
    ('fizika', 98, false),
    ('sifatli', 99, true),
    ('barcha javoblar to''g''ri', 99, false),
    ('yomon', 99, false),
    ('oqar', 99, false),
    ('burchak ichida tabiiy ishga yaroq yo\'lni to\'g\'ri tartibda ifodalash', 100, true),
    ('uchbilish qo\'llanmasi bilan kattalashish', 100, false),
    ('biriktirilgan burchakka o\'tkazilish', 100, false),
    ('jihazlarni qo\'llab-quvvatlash', 100, false),
    ('retseptorlarining blokadi', 101, true),
    ('retseptorlarining jadal tizilishi', 101, false),
    ('retseptorlarining ish xususiyatlari', 101, false),
    ('retseptorlarining orqaga solishini ta''minlash', 101, false);
-- Inserting new questions
INSERT INTO "question" ("text", "teacher_id") VALUES
    ('O''tkir qoringa gumon bo''lganda qanday qo''shimcha diagnostik tekshiruvlar o''tkazish kerak:', '1'),
    ('Chaqaloqlarda yurak - o''pka reanimatsiyasi o''tkazilishida yurak massaji va nafas nisbati qanday?', '1'),
    ('Tomir urishini sekinlashishi qanday nomlanadi?', '1'),
    ('Siydik tutilishi nima deyiladi', '1'),
    ('Jgut qo''yishning a’sorati:', '1'),
    ('Oshqozon-ichakdan qon ketish belgilari:', '1'),
    ('Plevra bo’shlig''ida yiring va havo borligi nima deyiladi?', '1'),
    ('Qon ketishida ishlatiladigan dori preparatlarni belgilang?', '1'),
    ('Quturish qanday bosqichlarda kechadi?', '1'),
    ('Tizza soxasiga qo''yiladigan bog''lam:', '1'),
    ('Diuretiklar va degidratsiyalovchi vositalar guruxini aniqlang?', '1'),
    ('Kuyish shokning erektil fazasidagi asosiy belgilar:', '1'),
    ('Antropometriya o''lchamlari bu:', '1'),
    ('Rektomanoskopiya tekshirish usuli bu-:', '1'),
    ('Irrigoskopiya qanday tekshirish usuli?', '1'),
    ('Normada bolalarning nafas olish soni 1 daqiqada qancha?', '1'),
    ('Nosteriod yallig''lanishga qarshi preparatni aniqlang?', '1'),
    ('Arterial qon ketishini uzil-kesil to’xtatish usulini aniqlang:', '1'),
    ('Antiseptika nima?', '1'),
    ('"Anesteziya" atamasi nimani anglatadi?', '1'),
    ('Qon ivuvchanligi va fibrinolizga ta''sir qiluvchi preparatlar qatorini aniqlang:', '1'),
    ('Kislorod bilan davolash usuli qanday nomlanadi?', '1'),
    ('Nafas yo''llari orqali kiruvchi zaxarli moddani aniklang:', '1'),
    ('Miorelaksantlarni nima maqsadda qo''llaniladi?', '1'),
    ('Eritrositlar va gemoglobinning pasayishi nimaga sabab bo''ladi?', '1'),
    ('Urologik bemorlarga xos simptomni aniqlang:', '1'),
    ('1 yoshdan 8 yoshgacha bolalarda tashqi yurak massaji quyidagicha amalga oshiriladi:', '1'),
    ('Zaharlanishlarda oshqozon yuvish uchun qancha suv kerak buladi?', '1'),
    ('Shokning erektil bosqichida qanday o''zgarish bo''ladi?', '1'),
    ('Qoqsholni oldini olish uchun qilinadigan choralar:', '1'),
    ('Kuyish shokida birinchi yordamga kirmaydi?', '1'),
    ('Zaxarli modda teri orqali kirganda qanday muolaja qilinadi?', '1'),
    ('O''tqir buyrak sanchig''ida shoshilinch yordam:', '1'),
    ('Jaroxat infektsiyasini oldini olishning eng samarali usuli:', '1'),
    ('Quturishning erta klinik belgilari:', '1'),
    ('Kichik qon aylanish doirasi qayerdan boshlanadi?', '1'),
    ('Buyrakda siydik ajralishini to''xtashi nima deb ataladi?', '1'),
    ('Allergik reaktsiyaning og''ir turi', '1'),
    ('Strangulyasion asfiksiya bu?', '1'),
    ('Gemostatiklar to’g''ri ko’rsatilgan qatorni ko’rsating:', '1');

-- Inserting choices for new questions
-- For each question, only the first choice is marked as correct (is_correct = true)
INSERT INTO "choices" ("question_id", "choice_text", "is_correct") VALUES
    ('21', '1umumiy R-grafiya', true),
    ('21', 'torakoskopiya', false),
    ('21', 'laparostentez', false),
    ('21', 'umumiy urografiya', false),

    ('22', '3:1', true),
    ('22', '30:2', false),
    ('22', '15:1', false),
    ('22', '5:1', false),

    ('23', '1Bradikardiya', true),
    ('23', 'taxikardiya', false),
    ('23', 'ekstrosistoliya', false),
    ('23', 'asistoliya', false),

    ('24', '1Anuriya', true),
    ('24', 'oliguriya', false),
    ('24', 'anuriya', false),
    ('24', 'gematuriya', false),

    ('25', '1nekroz, anaerob infeksiyaning rivojlanishi', true),
    ('25', 'qon to''xtamasligi, qattiq og''riqlar', false),
    ('25', 'anaerob infeksiyaning rivojlanishi qattiq og''riqlar', false),
    ('25', 'tromboflebit, qon tomirlar sklerozi', false),

    ('26', '1melena, umumiy xolsizlik bosh aylanishi "kofe rangi"dagi qusish', true),
    ('26', '“kofe rangi" dagi ko''piksimon qusish, umumiy xolsizlik', false),
    ('26', 'qonni qizil rangda bo''lishi, ko''piksimon melena, bosh aylanishi', false),
    ('26', 'yo''tal bilan bog''lik bo''lgan qon ketish, bosh aylanishi', false),

    ('27', '1Piopnevmotoraks', true),
    ('27', 'gidrotoraks', false),
    ('27', 'gematoraks', false),
    ('27', 'pnevmotoraks', false),

    ('28', '1vikasol, disinon', true),
    ('28', 'etamzilat, askarbin kislotasi', false),
    ('28', 'kaltsiy xlor, kaltsiy glyukanat', false),
    ('28', 'to''g''ri javob berilmagan', false),

    ('29', '1prodromal, qo''zg''alish, falajlik', true),
    ('29', 'kompensator, subkompensator, dekompensator', false),
    ('29', 'qo''zg''alish, prodromal, falajlik', false),
    ('29', 'kompensator, dekompensator, subkompensator', false),

    ('30', '1Toshbaqasimon', true),
    ('30', 'boshoqsimon', false),
    ('30', 'spiralsimon', false),
    ('30', 'aylanasimon', false),

    ('31', '1laziks, uregit, furasemid', true),
    ('31', 'kaltsiy glyukanat, eufullin', false),
    ('31', 'vikasol, ditsinon', false),
    ('31', 'papaverin gidroxlorid', false),

    ('32', '1asabning qattiq qo''zg''alishi, og''riqdan baqirishi', true),
    ('32', 'o''zini qayerga qo''yishni bilmaslik, bradikardiya', false),
    ('32', 'Q/B pasayishi va tomir urishining ipsimon bo''lishi', false),
    ('32', 'Alaxsirash, og''riqdan baqirishi', false),

    ('33', '1gavda vaznini va bo''yini o''lchash', true),
    ('33', 'ko''krak va bo’yini o’lchash', false),
    ('33', 'katta liqildokni o’lchash', false),
    ('33', 'bosh aylanasini o''lchash', false),

    ('34', '1to''g''ri ichak shilliq pardasini ko''zdan kechirish', true),
    ('34', 'qorin bo''shlig''ini ko''zdan kechirish', false),
    ('34', 'yo''g''on ichak shilliq pardasini ko''zdan kechirish', false),
    ('34', '12 barmoq ichak shilliq pardasini ko''zdan kechirish', false),

    ('35', '1yo''g''on ichakni rentgen tekshiruvi', true),
    ('35', 'to''g''ri ichakni rentgen tekshiruvi', false),
    ('35', 'ingichka ichakni rentgen tekshiruvi', false),
    ('35', 'me''da osti bezini rentgen tekshiruvi', false),

    ('36', '1 15-30', true),
    ('36', '12-20', false),
    ('36', '25-50', false),
    ('36', '8-10', false),

    ('37', '1Ibufen', true),
    ('37', 'dibazol', false),
    ('37', 'enap', false),
    ('37', 'geparin', false),

    ('38', '1tomirni bog''lash', true),
    ('38', 'bosib turuvchi bog''lam', false),
    ('38', 'tamponada', false),
    ('38', 'jgut qo''yish', false),

    ('39', '1jaroxatdagi mikroblarni o''ldirish', true),
    ('39', 'jaroxatga mikroblar tulishining oldini olish', false),
    ('39', 'kasallik chaqiruvchi mikroblarni o''ldirish', false),
    ('39', 'barcha tur mikroblarni yo''qotish', false),

    ('40', '1og''riqsizlantirish', true),
    ('40', 'to’g’ri javob yo’q', false),
    ('40', 'neyro-vegetativ blokada', false),
    ('40', 'jonlantirish', false),

    ('41', '1barcha javoblar to''g''ri', true),
    ('41', 'geparin', false),
    ('41', 'vikasol', false),
    ('41', 'aminakapronovaya kislota, ditsinon', false),

    ('42', '1Oksigenoterapiya', true),
    ('42', 'gidroterapiya', false),
    ('42', 'fitoterapiya', false),
    ('42', 'girudoterapiya', false),

    ('43', '1is gazi', true),
    ('43', 'morfin', false),
    ('43', 'ilon zaxri', false),
    ('43', 'vodorod peroksid', false),

    ('44', '1tana mushaklari tonusini bo''shashtirish uchun', true),
    ('44', 'tana mushaklari tonusini oshirish uchun', false),
    ('44', 'tana mushaklari qo''zg''aluvchanligini oshirish uchun', false),
    ('44', 'qon bosimini tushurish uchun', false),

    ('45', '1To’qimalarga kislorod tashib berish xususiyatining pasayishiga', true),
    ('45', 'To''qimalarga oqsillarning tashish xususiyatining pasayishiga', false),
    ('45', 'To''qimalarga uglevodlar tashish xususiyatinigg pasayishiga', false),
    ('45', 'To''qimalarga mikroelementlar tashish xususiyatining pasayishiga', false),

    ('46', '1gematuriya', true),
    ('46', 'disfagiya', false),
    ('46', 'axiliya', false),
    ('46', 'melanxoliya', false),

    ('47', '1bir qo''lning kaft asosi bilan', true),
    ('47', 'o''rta barmoq uchlari bilan', false),
    ('47', 'ikki qo''lning kaft asoslari bilan', false),
    ('47', 'to''g''ri javob yo''q', false),

    ('48', '1    10-15 l uy haroratdagi suv', true),
    ('48', '2 - 3 stakan iliq suv', false),
    ('48', '2 - 3 litr sovuq suv', false),
    ('48', 'oqozoni yuvish shart emas', false),

    ('49', '1ko''z qorachig''i kengaygan, yuzlari qizargan, AB birmuncha baland', true),
    ('49', 'AB 100/60 mm simob ustuni, puls tezlashgan, terisi oqargan', false),
    ('49', 'bemorning rangi bo''zargan, sovuq ter bosgan, kam gapiradi', false),
    ('49', 'bemor savollarga qiyinchillik bilan javob beradi, terisi oqargan, puls 130marta ipsimon', false),

    ('50', '1jaroxatni yot jismlardan tozalash, qoqshol anatoksini va qoqsholga qarshi zardob qilish', true),
    ('50', 'axoli orasida sanitar ishlarini olib borish', false),
    ('50', 'jaroxatni o''lik to''qimadan tozalash, travmatizmga qarshi kurashish', false),
    ('50', 'barcha mollarni veterinar nazoratdan o''tkazish', false),

    ('51', '1kuygan joyga jgut quyish', true),
    ('51', 'og''riq koldiruvchi preparatlarni qo''llash', false),
    ('51', 'yurak glikozidlarini qo''llash', false),
    ('51', 'shokka qarshi chora - tadbirlar', false),

    ('52', '1oqar suvda yuviladi', true),
    ('52', 'spirt suriladi', false),
    ('52', 'malxam suriladi', false),
    ('52', 'yod eritmasi suriladi', false),

    ('53', '1spazmolitiklarni qo''llash', true),
    ('53', 'og''riqsizlantirish', false),
    ('53', 'kateter quyish', false),
    ('53', 'Garmonoterapiya', false),

    ('54', '1jaroxatga birlamchi jarroxlik ishlovini berish', true),
    ('54', 'aseptik bog''lam qo''yish', false),
    ('54', 'antibiotiklarni venaga yuborish', false),
    ('54', 'jaroxatga proteolitik fermentlar yuborish', false),

    ('55', '1tishlangan sohada og''rik', true),
    ('55', 'eyforiya', false),
    ('55', 'krepitasiya', false),
    ('55', 'trizm', false),

    ('56', '1o''ng qorinchadan', true),
    ('56', 'o''ng bo''lmachadan', false),
    ('56', 'chap bo''lmachadan', false),
    ('56', 'chap qorinchadan', false),

    ('57', '1Anuriya', true),
    ('57', 'gematuriya', false),
    ('57', 'oliguriya', false),
    ('57', 'ishuriya', false),

    ('58', '1anafilaktik shok', true),
    ('58', 'dermatit', false),
    ('58', 'Kvinke shishi', false),
    ('58', 'eshakyemi', false),

    ('59', '1bo''yin bo''g''ilishi ezilishi oqibatida kekirdak va tomoq og''rishi', true),
    ('59', 'nafas yo''llari to''silib, ulardan xavo o''tmay qolishidir', false),
    ('59', 'nafas yo''llari obstruktsiyasi', false),
    ('59', 'bo''g''ilish oqibatida o''pkani ezilishi', false),

    ('60', '1aminokapron kislota, vikasol, disinon, kaltsiy xlorid', true),
    ('60', 'aminokapron kislota, vikasol, askorbin kislota, kaltsiy xlorid', false),
    ('60', 'aminokapron kislota, vikasol, disinon, vitamin E', false),
    ('60', 'vitaminlar', false);
